import { Injectable } from '@angular/core';
import { Post } from '../models/Post.model';

@Injectable({
  providedIn: 'root'
})
export class PostService {

  posts: Array<Post> = [
    {
      id: Math.floor(Math.random() * 2500),
      category: "technology",
      userOwner: "gurudatecnologia123",
      title: "The Latest in AI Technology",
      subtitle: "Exploring Cutting-Edge AI Advances",
      image: 'assets/img_test.jpg',
      content: "In this article, we will dive into the latest discoveries in artificial intelligence (AI) that are shaping our future. AI is becoming increasingly integrated into our lives, from virtual assistants to autonomous cars. We will explore how these innovations are impacting various sectors, from healthcare to transportation. Get ready for an exciting journey into the world of AI!",
      date: new Date("2023-09-18"),
      views: 2567,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "travel",
      userOwner: "aventurasviajantes",
      title: "Journey Through Europe",
      subtitle: "Discovering Hidden Treasures of Europe",
      image: 'assets/img_test.jpg',
      content: "Join us on an unforgettable journey through the picturesque landscapes and rich history of Europe. From the grandeur of historic cities to the serenity of seaside villages, we will explore the most charming destinations on this diverse continent. Prepare your travel wishlist because this is an adventure you won't want to miss!",
      date: new Date("2023-09-15"),
      views: 1789,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "culinary",
      userOwner: "mestreculinario",
      title: "Delicious Italian Cuisine",
      subtitle: "Preparing Authentic Italian Flavors",
      image: 'assets/img_test.jpg',
      content: "Learn the art of creating irresistible Italian dishes with our step-by-step guide. We will explore the secrets of Italian cuisine, from fresh pasta to classic dishes like lasagna and pizza. Additionally, discover the regions of Italy famous for their gastronomy and learn how to prepare these dishes in your own kitchen. Indulge in the taste of Italy!",
      date: new Date("2023-09-12"),
      views: 3256,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "health",
      userOwner: "vidasaudavel",
      title: "Wellness and Mindfulness",
      subtitle: "Achieving Balance in Your Life",
      image: 'assets/img_test.jpg',
      content: "Discover the practices and habits that can help you lead a more balanced and fulfilling life. In this article, we will explore the world of wellness and mindfulness, from meditation techniques to tips for improving mental health. Find inspiration to take care of yourself and achieve the balance we all desire.",
      date: new Date("2023-09-10"),
      views: 4321,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "science",
      userOwner: "geekdacincia",
      title: "Wonders of Space",
      subtitle: "Exploring the Mysteries Beyond Our Planet",
      image: 'assets/img_test.jpg',
      content: "Embark on a cosmic journey with us as we unravel the fascinating mysteries of the universe. From space exploration to the search for extraterrestrial life, this article will take you to places where science meets imagination. Learn more about distant planets, black holes, and the latest discoveries in astronomy. Get ready for a space adventure without leaving Earth!",
      date: new Date("2023-09-08"),
      views: 2890,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "fashion",
      userOwner: "divademoda",
      title: "High Fashion Trends",
      subtitle: "Stay Chic and Stylish with the Latest Fashion Trends",
      image: 'assets/img_test.jpg',
      content: "Get inspired by the hottest fashion trends that are taking the world by storm. From runway shows to everyday choices, discover how to embrace celebrity style and create your own unique look. Be ready to rock with the clothing, accessories, and fashion tips we'll share in this exclusive article!",
      date: new Date("2023-09-06"),
      views: 1987,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "sports",
      userOwner: "fanaticoesportivo",
      title: "Epic Sports Moments",
      subtitle: "Reliving the Most Memorable Sports Moments",
      image: 'assets/img_test.jpg',
      content: "Join us as we revisit the unforgettable moments in the world of sports. From the Olympics to football championships, we'll reminisce about incredible plays, historic achievements, and heartwarming stories that have shaped sports. Get ready for a dose of sports adrenaline and nostalgia!",
      date: new Date("2023-09-04"),
      views: 3765,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "culinary",
      userOwner: "amantedagastronomia",
      title: "Adventures in Gourmet Cuisine",
      subtitle: "Savoring the Flavors of Gourmet Cuisine",
      image: 'assets/img_test.jpg',
      content: "Experience the delights of gourmet cuisine from around the world. In this article, we'll take you on a culinary journey that includes exquisite dishes, rare ingredients, and unique gastronomic experiences. From Michelin-starred restaurants to recipes you can prepare at home, this is a feast for food lovers!",
      date: new Date("2023-09-02"),
      views: 2543,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "music",
      userOwner: "amantedamusica",
      title: "The Evolution of Rock Music",
      subtitle: "Tracing the History of Rock 'n' Roll",
      image: 'assets/img_test.jpg',
      content: "Take a musical journey through the decades to explore the evolution of rock music. From classic rock of the '60s to contemporary subgenres, this article will take you on a sonic adventure. Discover iconic artists, legendary songs, and moments that defined an era in music. Fasten your seatbelt, as this musical journey promises to be an electrifying experience!",
      date: new Date("2023-08-30"),
      views: 2134,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "travel",
      userOwner: "viajantedomundo",
      title: "Adventures in Asia",
      subtitle: "Discovering the Beauty of Asian Destinations",
      image: 'assets/img_test.jpg',
      content: "Embark on an unforgettable adventure through the diverse landscapes and cultures of Asia. From vibrant metropolises to stunning natural landscapes, we will explore what makes Asia so captivating. Discover the secrets of Asian cuisine, ancient temples, and colorful festivals that make this region a must-visit for travelers. Get ready for an exciting journey!",
      date: new Date("2023-08-28"),
      views: 3456,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "technology",
      userOwner: "entusiastadatecnologia",
      title: "The Future of Smart Homes",
      subtitle: "Exploring Innovations in Home Automation",
      image: 'assets/img_test.jpg',
      content: "Get a glimpse of the future of life with advanced smart home technologies. In this article, we'll explore the latest trends in home automation, from advanced security systems to virtual assistants that make life more convenient. Discover how artificial intelligence is transforming our homes into more efficient and comfortable spaces. Welcome to the home of the future!",
      date: new Date("2023-08-26"),
      views: 2890,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "health",
      userOwner: "jornadadebemestar",
      title: "Holistic Health Practices",
      subtitle: "Taking Care of Mind, Body, and Soul",
      image: 'assets/img_test.jpg',
      content: "Discover holistic practices that can enhance your overall well-being. In this article, we'll explore meditation techniques, alternative therapies, and strategies to achieve harmony in your life. Holistic health addresses all aspects of your existence, and we're here to guide you on a journey of self-discovery and balance. Get ready for a complete transformation!",
      date: new Date("2023-08-24"),
      views: 1987,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "science",
      userOwner: "geekdaciencia",
      title: "Wonders of Marine Life",
      subtitle: "Exploring Secrets Beneath the Waves",
      image: 'assets/img_test.jpg',
      content: "Dive into the depths of the ocean to discover the incredible world of marine life. In this article, we'll explore vibrant coral reefs, fascinating marine creatures, and the mysteries that inhabit the oceans. From bioluminescence to whale migrations, you'll be amazed by the diversity of marine life. Come with us on this aquatic adventure!",
      date: new Date("2023-08-22"),
      views: 3765,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "fashion",
      userOwner: "fashionista",
      title: "Elegant Evening Attire",
      subtitle: "A Guide to Dressing for Special Occasions",
      image: 'assets/img_test.jpg',
      content: "Discover the secrets of looking elegant and sophisticated in evening attire. In this article, we'll explore fashion trends for nighttime events, from dazzling dresses to accessories that make a difference. Find inspiration to create a look that reflects your style and personality at parties, weddings, and special occasions. You'll be the star of the night!",
      date: new Date("2023-08-20"),
      views: 2543,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "sports",
      userOwner: "entusiastaesportivo",
      title: "Legendary Athletes of All Time",
      subtitle: "Celebrating Icons in Sports History",
      image: 'assets/img_test.jpg',
      content: "Pay tribute to the greatest athletes who have left an indelible mark on the world of sports. In this article, we highlight brilliant careers, memorable victories, and incredible feats that have made history. From football fields to Olympic stadiums, revisit the exciting moments provided by these legendary athletes. This is a tribute to sports heroes!",
      date: new Date("2023-08-18"),
      views: 2134,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "culinary",
      userOwner: "exploradordegourmet",
      title: "Street Food Delights",
      subtitle: "Tasting the Best Street Foods from Around the World",
      image: 'assets/img_test.jpg',
      content: "Embark on a culinary journey that will take you to the tastiest street food stalls around the world. In this article, we'll explore street dishes that represent the authenticity of global cuisine, from Mexican tacos to Turkish kebabs. Meet talented street chefs and discover the stories behind their delicious creations. Get ready for a gastronomic adventure!",
      date: new Date("2023-08-16"),
      views: 3456,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "travel",
      userOwner: "viajantedeaventuras",
      title: "Exploring Natural Wonders",
      subtitle: "Discovering Breathtaking Landscapes Around the World",
      image: 'assets/img_test.jpg',
      content: "Venture into untouched trails, secluded beaches, and breathtaking landscapes in this exciting travel article. Explore incredible destinations that are true natural wonders, from snowy mountain peaks to crystal-clear lake waters. Get to know exotic wildlife and immerse yourself in the beauty of the natural world. Get ready for an epic journey through the Earth!",
      date: new Date("2023-08-14"),
      views: 2876,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "health",
      userOwner: "vidafitness",
      title: "The Science of Physical Well-Being",
      subtitle: "Discovering the Secrets to a Healthy Life",
      image: 'assets/img_test.jpg',
      content: "This article delves deep into the science behind physical well-being. Discover the best practices for maintaining a healthy life, from proper nutrition to the importance of regular exercise. Understand how the human body works and how you can optimize your health. This is the ultimate guide to an active and balanced life!",
      date: new Date("2023-08-12"),
      views: 3421,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "culinary",
      userOwner: "gourmetculinary",
      title: "The Art of Fine Dining",
      subtitle: "Exploring High-Quality Cuisine",
      image: 'assets/img_test.jpg',
      content: "Enter the sophisticated world of fine dining, where food is a form of art. This article will take you to award-winning restaurants and present exquisite dishes prepared by renowned chefs. Discover rare ingredients, advanced culinary techniques, and perfect wine pairings. Get ready for a unique and luxurious gastronomic experience!",
      date: new Date("2023-08-10"),
      views: 2139,
    },
    {
      id: Math.floor(Math.random() * 2500),
      category: "fashion",
      userOwner: "estilofashion",
      title: "The Power of Personal Style",
      subtitle: "Expressing Your Individuality Through Fashion",
      image: 'assets/img_test.jpg',
      content: "Fashion is a form of personal expression, and in this article, we'll explore how you can find and develop your own unique style. From vintage clothing to contemporary pieces, learn how to build a wardrobe that reflects your personality and creativity. Discover style tips, current trends, and how fashion can be a form of empowerment. This is the ultimate guide to unlocking the power of your personal style!",
      date: new Date("2023-08-08"),
      views: 1765,
    },
  ];


  constructor() { }

  getPosts(): Array<Post> {
    return this.posts;
  }

  getPostById(id: number): Post {
    const target = this.posts.find(post => post.id === id)
    if (target) {
      return target
    }
    throw new Error('Undefined Post')
  }
}
